reference:
  # dna: /home/jiezhu/databases/ensembl/release_104/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz
  # dna: /home/jiezhu/databases/ensembl/release_104/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  # dna: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/GRCm39.primary_assembly.genome.fa.gz
  dna: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/GRCh38.primary_assembly.genome.fa.gz

  # cdna: /home/jiezhu/databases/ensembl/release_104/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz
  # cdna: /home/jiezhu/databases/ensembl/release_104/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
  # cdna: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/gencode.vM28.transcripts.fa.gz
  cdna: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/gencode.v39.transcripts.fa.gz

  # gtf: /home/jiezhu/databases/ensembl/release_104/gtf/mus_musculus/Mus_musculus.GRCm39.104.gtf
  # gtf: /home/jiezhu/databases/ensembl/release_104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.gtf
  # gtf: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/gencode.vM28.primary_assembly.annotation.gtf
  gtf: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/gencode.v39.primary_assembly.annotation.gtf

  # index_rsem: /home/jiezhu/databases/ensembl/release_104/fasta/mus_musculus/dna_index/index_rsem/mus_musculus
  # index_rsem: /home/jiezhu/databases/ensembl/release_104/fasta/homo_sapiens/dna_index/index_rsem/homo_sapiens
  # index_rsem: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/index_rsem/mus_musculus
  index_rsem: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/index_rsem/homo_sapiens

  # index_star: /home/jiezhu/databases/ensembl/release_104/fasta/mus_musculus/dna_index/index_star
  # index_star: /home/jiezhu/databases/ensembl/release_104/fasta/homo_sapiens/dna_index/index_star
  # index_star: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/index_star
  index_star: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/index_star

  # index_salmon: /home/jiezhu/databases/ensembl/release_104/fasta/mus_musculus/cdna_index/index_salmon
  # index_salmon: /home/jiezhu/databases/ensembl/release_104/fasta/homo_sapiens/cdna_index/index_salmon
  # index_salmon: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/index_salmon
  index_salmon: /home/jiezhu/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/index_salmon


params:
  samples: "samples.tsv"
  fq_encoding: "sanger" # fastq quality encoding. available values: 'sanger', 'solexa', 'illumina-1.3+', 'illumina-1.5+', 'illumina-1.8+'. (default "sanger")
  reads_layout: "pe"
  interleaved: False
  strandedness: "reverse" # "", "forward", "reverse"

  raw:
    threads: 8
    save_reads: True
    fastqc:
      do: False

  trimming:
    save_reads: True
    fastp:
      do: True
      threads: 4
      use_slide_window: False # strict when using slide window
      disable_adapter_trimming: False
      detect_adapter_for_se: True # If activated, adapter_sequence will not used
      detect_adapter_for_pe: True # If activated, adapter_sequence and adapter_sequence_r2 will not used
      adapter_sequence: "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA" # MGI adapter 3
      adapter_sequence_r2: "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG" # MGI adapter 5
      # "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"         # eg: Illumina TruSeq adapter 3
      # "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"         # eg: Illumina TruSeq adapter 5
      compression: 6
      cut_front_window_size: 4
      cut_front_mean_quality: 20
      cut_tail_window_size: 4
      cut_tail_mean_quality: 20
      cut_right_window_size: 4
      cut_right_mean_quality: 20
      length_required: 51
      n_base_limit: 5
      dedup: False
      dup_calc_accuracy: 3 # [1, 2, 3, 4, 5, 6] # only used when dedup: True

  delriborna:
    threads: 8
    ribodetector:
      do: True
      GPU: True
      reads_len: 100
      chunk_size: 256 # control memory usage when using CPU
      extra: "--memory 12" # only work for GPU

  qcreport:
    do: True
    seqkit:
      threads: 4

  align:
    threads: 8
    star:
      do: True
      quant_mode:
        TranscriptomeSAM: True
        # output SAM/BAM alignments to transcriptome into a separate file
        GeneCounts: False
        # count reads per gene

  quantify:
    threads: 8 
    salmon:
      do: True
      index_add_genome: True
      kmer_len: 31
      lib_type: "A" # To allow Salmon to automatically infer the library type, simply provide -l A or --libType A to Salmon
      extra: "--gcBias"

  assembly:
    threads: 8 
    trust4:
      do: True
      coordinate_fasta: "/home/zhujie/databases/funcgenomics/IMGT/TRUST4/Homo_sapien/human_IMGT+C.fa"
      reference_fasta: "/home/zhujie/databases/funcgenomics/IMGT/TRUST4/Homo_sapien/human_IMGT+C.fa"

  hlatyping:
    threads: 8
    arcashla:
      do: True
      IMGTHLA_version: 3.46.0 # latest
      unmapped: False
      genes: ["DPB1", "DRB1", "DRA", "L", "K", "B", "DOB", "DRB3", "DMA", "G", "DMB", "C", "DQA1", "DOA", "F", "E", "DPA1", "DRB5", "DQB1", "H", "A", "J"]
      # genes: ["A", "B", "C", "DPB1", "DQA1", "DQB1", "DRB1"]
      # population: ["prior", "native_american", "asian_pacific_islander", "caucasian", "black", "hispanic"]

output:
  raw: "results/00.raw"
  trimming: "results/01.trimming"
  delriborna: "results/02.delriborna"
  qcreport: "results/02.qcreport"
  align: "results/03.align"
  quantify: "results/04.quantify"
  assembly: "results/05.assembly"
  hlatyping: "results/06.hlatyping"


envs:
  fastp: "envs/fastp.yaml"
  multiqc: "envs/multiqc.yaml"
  delriborna: "envs/delriborna.yaml"
  align: "envs/align.yaml"
  trust4: "envs/trust4.yaml"
  arcashla: "envs/arcashla.yaml"
