reference:
  dna: /home/zhujie/databases/ensembl/release_104/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz
  # dna: /home/zhujie/databases/ensembl/release_104/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz
  dna_gencode: /home/zhujie/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/GRCm39.primary_assembly.genome.fa.gz
  # dna_gencode: /home/zhujie/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/GRCh38.primary_assembly.genome.fa.gz

  cdna: /home/zhujie/databases/ensembl/release_104/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz
  # cdna: /home/zhujie/databases/ensembl/release_104/fasta/homo_sapiens/cdna/Homo_sapiens.GRCh38.cdna.all.fa.gz
  cdna_gencode: /home/zhujie/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/gencode.vM28.transcripts.fa.gz
  # cdna_gencode: /home/zhujie/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_39/gencode.v39.transcripts.fa.gz

  gtf: /home/zhujie/databases/ensembl/release_104/gtf/mus_musculus/Mus_musculus.GRCm39.104.gtf
  # gtf: /home/zhujie/databases/ensembl/release_104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.gtf

  index_star: /home/zhujie/databases/ensembl/release_104/fasta/mus_musculus/dna_index/index_star # index directory
  index_rsem: /home/zhujie/databases/ensembl/release_104/fasta/mus_musculus/dna_index/index_rsem/mus_musculus # index prefix
  # index_salmon: /home/zhujie/databases/ensembl/release_104/fasta/mus_musculus/cdna_index/index_salmon # index directory
  index_salmon: /home/zhujie/databases/ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M28/index_salmon # index directory

params:
  samples: "samples.tsv"
  fq_encoding: "sanger" # fastq quality encoding. available values: 'sanger', 'solexa', 'illumina-1.3+', 'illumina-1.5+', 'illumina-1.8+'. (default "sanger")
  reads_layout: "pe"
  interleaved: False
  strandedness: "reverse" # "", "forward", "reverse"

  raw:
    threads: 8
    save_reads: True
    fastqc:
      do: False

  trimming:
    fastp:
      do: True
      threads: 4
      use_slide_window: False # strict when using slide window
      disable_adapter_trimming: False
      detect_adapter_for_se: True # If activated, adapter_sequence will not used
      detect_adapter_for_pe: True # If activated, adapter_sequence and adapter_sequence_r2 will not used
      adapter_sequence: "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA" # MGI adapter 3
      adapter_sequence_r2: "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG" # MGI adapter 5
      # "AGATCGGAAGAGCACACGTCTGAACTCCAGTCA"         # eg: Illumina TruSeq adapter 3
      # "AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"         # eg: Illumina TruSeq adapter 5
      compression: 6
      cut_front_window_size: 4
      cut_front_mean_quality: 20
      cut_tail_window_size: 4
      cut_tail_mean_quality: 20
      cut_right_window_size: 4
      cut_right_mean_quality: 20
      length_required: 51
      n_base_limit: 5

  delriborna:
    threads: 8
    ribodetector:
      do: True
      GPU: True
      reads_len: 100
      chunk_size: 256 # control memory usage when using CPU
      extra: "--memory 12" # only work for GPU

  qcreport:
    do: True
    seqkit:
      threads: 4

  align:
    threads: 8
    star:
      do: True
      quant_mode:
        TranscriptomeSAM: True
        # output SAM/BAM alignments to transcriptome into a separate file
        GeneCounts: False
        # count reads per gene

  quantify:
    threads: 32
    salmon:
      do: True
      index_add_genome: True
      kmer_len: 31
      lib_type: "A" # To allow Salmon to automatically infer the library type, simply provide -l A or --libType A to Salmon
      extra: "--gcBias"

  assembly:
    threads: 32
    trust4:
      do: True
      coordinate_fasta: "/home/zhujie/databases/funcgenomics/IMGT/TRUST4/Homo_sapien/human_IMGT+C.fa"
      reference_fasta: "/home/zhujie/databases/funcgenomics/IMGT/TRUST4/Homo_sapien/human_IMGT+C.fa"


output:
  raw: "results/00.raw"
  trimming: "results/01.trimming"
  delriborna: "results/02.delriborna"
  qcreport: "results/02.qcreport"
  align: "results/03.align"
  quantify: "results/04.quantify"
  assembly: "results/05.assembly"


envs:
  bioenv3.8: "envs/bioenv3.8.yaml"
